DEV: add lib.exe to path

diff --git a/.github/actions/build-iqtree/action.yml b/.github/actions/build-iqtree/action.yml
--- a/.github/actions/build-iqtree/action.yml
+++ b/.github/actions/build-iqtree/action.yml
@@ -43,6 +43,23 @@ runs:
         echo "Boost_INCLUDE_DIR=${{ steps.install-boost.outputs.BOOST_ROOT }}/include" >> "$GITHUB_ENV"
         echo "Boost_LIBRARY_DIRS=${{ steps.install-boost.outputs.BOOST_ROOT }}/lib" >> "$GITHUB_ENV"
 
+    - name: Set Up MSVC for lib.exe
+      if: runner.os == 'Windows' && steps.cache.outputs.cache-hit != 'true'
+      shell: bash
+      run: |
+        MSVC_BIN_PATH="C:\\Program Files\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC"
+        MSVC_VERSION=$(ls "$MSVC_BIN_PATH" | sort -V | tail -n 1)
+        LIB_PATH="$MSVC_BIN_PATH\\$MSVC_VERSION\\bin\\Hostx64\\x64"
+        
+        echo "Adding $LIB_PATH to PATH"
+        echo "PATH=$LIB_PATH:$PATH" >> "$GITHUB_ENV"
+
+    - name: Verify lib.exe
+      if: runner.os == 'Windows' && steps.cache.outputs.cache-hit != 'true'
+      shell: bash
+      run: |
+        which lib.exe || echo "lib.exe not found"
+
     - name: Build IQ-TREE
       shell: bash
       if: steps.cache.outputs.cache-hit != 'true'
